branches:
  only:
    - master
matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "6"
      script: npm run lint
    - stage: "WebPack"
      os: osx
      env:
        - Platform="iOS"
      osx_image: xcode8.3
      language: node_js
      node_js: "6"
      jdk: oraclejdk8
      script: npm run build-ios-bundle
    - language: android
      os: linux
      env:
        - Platform="Android"
      jdk: oraclejdk8
      before_install: nvm install 6.10.3
      script: npm run build-android-bundle
    - stage: "Build"
      env:
        - Android="25"
      language: android
      os: linux
      jdk: oraclejdk8
      before_install: nvm install 6.10.3
      script: npm run build-android
    - os: osx
      env:
        - iOS="10.3"
        - Xcode="8.3"
      osx_image: xcode8.3
      language: node_js
      node_js: "6"
      jdk: oraclejdk8
      script: npm run build-ios

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable